continents = ['North America', 'South America', 'Antarctica', 'Oceania',  'Africa', 'Europe', 'Asia',]
print(continents)
continents.sort()
print(continents)
continents.sort(reverse=True)
print(continents)
print(sorted(continents))
print(continents)
continents.sort(reverse=False)
print(continents)
continents.reverse()
print(continents)
print(len(continents))
print(continents[4])